name: Package CI

on:
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: iconv
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make composer

      - run: make phpstan

      - run: make tester
